import { useEffect, useState } from "react";
import { CheckIcon, ChevronIcon, CpuIcon, FileIcon, FolderIcon, PlayIcon, SparkIcon, TelescopeIcon } from "./icons";
import { useI18n, type Translator, type UiLanguage } from "./i18n";
import { CalibrationGroups, FrameInventory, InputChecks } from "./FrameInventory";
import type { GateDisposition, MasterMetadataOverride, OutputArtifactKind, ScreeningSummary, WorkflowStep } from "./types";
import { useWorkflow } from "./useWorkflow";

const PASS_FRAME_BATCH = 50;
const basename = (path: string) => path.split(/[\\/]/).filter(Boolean).pop() ?? path;
const formatBytes = (bytes: number, t: Translator) => bytes ? `${(bytes / 1_000_000).toFixed(0)} MB` : t("externallyManaged");
const optionalNumber = (value: string) => value.trim() === "" ? null : Number(value);
const formatElapsed = (seconds: number) => [Math.floor(seconds / 3600), Math.floor(seconds / 60) % 60, seconds % 60].map((value) => String(value).padStart(2, "0")).join(":");
// Import, the optional screening review and the launch settings are one user
// step; processing and the result are the other two.
const userStep = (step: WorkflowStep) => step === "import" || step === "inspect" ? 0 : step === "run" ? 1 : 2;

function artifactLabel(kind: OutputArtifactKind, t: Translator): string {
  return {
    SOLVED_MONO_FITS: t("artifactSolvedMono"), LINEAR_RGB_FITS: t("artifactLinearRgb"), RGB_PREVIEW_TIFF_16: t("artifactTiff"), RGB_PREVIEW_PNG_16: t("artifactPng"), MONO_PREVIEW_PNG: t("artifactMonoPreview"), RECEIPT: t("artifactReceipt"), REPORT: t("artifactReport"), DRIZZLE_DATA: t("artifactDrizzle"), MASTER: t("artifactMaster"), PREVIEW: t("artifactPreview"),
  }[kind];
}

function stageLabel(stageId: string, t: Translator): string {
  return {
    "quality-control": t("stageQuality"), calibrate: t("stageCalibration"), register: t("stageRegistration"), "local-normalization": t("stageLocalNormalization"), integrate: t("stageIntegration"), drizzle: t("stageDrizzle"), solve: t("stageSolve"), mosaic: t("stageMosaic"), color: t("stageColor"), prepare: t("stagePrepare"), alignment: t("stageAlignment"), preview: t("stagePreview"), verify: t("stageVerify"), publish: t("stagePublish"),
  }[stageId] ?? stageId;
}

function RunElapsed({ seconds, label }: { seconds: number; label: string }) {
  return <div className="run-elapsed"><span>{label}</span><output role="timer" aria-label={label}>{formatElapsed(seconds)}</output></div>;
}

function App() {
  const { language, setLanguage, t } = useI18n();
  const workflow = useWorkflow(t);
  const [inputPathsText, setInputPathsText] = useState("");
  const [outputPathText, setOutputPathText] = useState("");
  const [visiblePassFrames, setVisiblePassFrames] = useState(PASS_FRAME_BATCH);
  useEffect(() => setVisiblePassFrames(PASS_FRAME_BATCH), [workflow.qualityInspection]);
  const currentStep = userStep(workflow.step);
  const targets = [...new Set(workflow.matrix.map((cell) => cell.target))];
  const filters = [...new Set(workflow.matrix.map((cell) => cell.filter))];
  const lightCount = workflow.sources.find((source) => source.role === "LIGHT")?.fileCount ?? 0;
  const issueQualityFrames = workflow.qualityInspection?.frames.filter((frame) => frame.disposition !== "PASS") ?? [];
  const passingQualityFrames = workflow.qualityInspection?.frames.filter((frame) => frame.disposition === "PASS") ?? [];
  const displayedQualityFrames = [...issueQualityFrames, ...passingQualityFrames.slice(0, visiblePassFrames)];
  const userSteps = [
    { label: t("stepImport"), caption: t("stepImportCaption"), target: "import" as WorkflowStep },
    { label: t("stepProcess"), caption: t("stepProcessCaption"), target: "run" as WorkflowStep },
    { label: t("stepResult"), caption: t("stepResultCaption"), target: "result" as WorkflowStep },
  ];
  const launchPanel = (mode: "import" | "inspect") => <LaunchPanel mode={mode} workflow={workflow} outputPathText={outputPathText} setOutputPathText={setOutputPathText} lightCount={lightCount} t={t} />;

  const metadataConfirmations = <div id="metadata-confirmations" className="metadata-confirmations">
    {workflow.assets.length > 0 && <p className="calibration-mode-note">{t("monoStandardDefaults")}</p>}
    {workflow.cfaBlockedAssets.length > 0 && <Alert title={t("cfaBlockedTitle")}>{t("cfaBlockedBody", { count: workflow.cfaBlockedAssets.length })}</Alert>}
    {workflow.masterOverrides.length > 0 && <details className="progressive-panel master-section"><summary><span>{t("masterTitle")}</span><small>{t("optionalOverrides")}</small></summary><div className="details-content"><p>{t("masterBody")}</p><div className="master-form-grid">{workflow.masterOverrides.map((item) => <MasterForm key={item.sourceSha256} item={item} update={(patch) => workflow.updateMasterOverride(item.sourceSha256, patch)} confirm={() => workflow.confirmMasterOverride(item.sourceSha256)} reset={() => workflow.resetMasterOverride(item.sourceSha256)} t={t} />)}</div></div></details>}
  </div>;

  return <div className="app-shell" onContextMenu={(event) => { if (!(event.target instanceof Element) || !event.target.closest("input, textarea, [contenteditable=true]")) event.preventDefault(); }}>
    <a className="skip-link" href="#workspace">{t("skipWorkspace")}</a><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="topbar" data-tauri-drag-region="deep"><div className="brand" aria-label="Ultra-Fast WBPP"><span className="brand-mark"><SparkIcon /></span><span><strong>ULTRA-FAST</strong> <em>WBPP</em></span>{!workflow.nativeRuntime && <span className="preview-badge">{t("browserDemo")}</span>}</div><div className="topbar-actions"><label className="language-picker" data-tauri-drag-region="false"><span>{t("language")}</span><select aria-label={t("language")} value={language} onChange={(event) => setLanguage(event.target.value as UiLanguage)}><option value="en">{t("english")}</option><option value="zh-CN">{t("chinese")}</option></select></label><div className="runtime-summary" aria-label={t("computeBackend")} role="status"><span className={`runtime-dot ${workflow.capabilities?.available ? "online" : ""}`} /><div><small>{workflow.capabilities?.available ? t("engineReady") : t("engineUnavailable")}</small><strong>{workflow.capabilities?.chip ?? t("detectingHardware")}</strong></div></div></div></header>
    <nav className="stepper" aria-label={t("workflowLabel")}>{userSteps.map((item, index) => { const state = index < currentStep ? "complete" : index === currentStep ? "active" : "upcoming"; const disabled = workflow.runNavigationLocked || workflow.inputBusy || index !== 0 || currentStep === 0; return <button type="button" key={item.target} className={`step ${state}`} aria-current={state === "active" ? "step" : undefined} onClick={() => !disabled && workflow.setStep(item.target)} disabled={disabled}><span className="step-number">{state === "complete" ? <CheckIcon /> : String(index + 1).padStart(2, "0")}</span><span><strong>{item.label}</strong><small>{item.caption}</small></span></button>; })}</nav>
    <main id="workspace" className="workspace">
      {workflow.step === "import" && <section aria-labelledby="import-title" className="page page-import"><PageHeading id="import-title" eyebrow={t("newProject")} title={t("importTitle")} description={t("importDescription")} />{workflow.errorMessage && <Alert title={t("operationFailed")}>{workflow.errorMessage}</Alert>}
        <div className={`drop-hero ${workflow.isDragging ? "dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); workflow.setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => workflow.setDragging(false)} onDrop={(event) => { event.preventDefault(); workflow.setDragging(false); }}><span className="drop-orbit"><FolderIcon /></span><div><strong>{workflow.inventoryBusy ? t("readingMetadata") : workflow.nativeRuntime ? t("dropNative") : t("dropBrowser")}</strong><p>{workflow.selectedRole ? t("nextBatch", { role: workflow.selectedRole }) : t("autoRead")}</p>{workflow.selectedRole && <button type="button" className="text-button" disabled={workflow.inputBusy} onClick={() => workflow.setSelectedRole(undefined)}>{t("autoDetect")}</button>}</div><div className="dialog-actions"><button className="secondary-button" type="button" disabled={!workflow.nativeRuntime || workflow.inputBusy} onClick={() => void workflow.pickFiles(workflow.selectedRole)}>{t("chooseFiles")} <ChevronIcon /></button><button className="secondary-button" type="button" disabled={!workflow.nativeRuntime || workflow.inputBusy} onClick={() => void workflow.pickDirectories(workflow.selectedRole)}>{t("chooseFolder")} <FolderIcon /></button></div></div>
        {workflow.nativeRuntime && <details className="progressive-panel path-entry-panel"><summary><span>{t("pasteInputPaths")}</span></summary><form className="details-content path-entry-form" onSubmit={(event) => { event.preventDefault(); const paths = [...new Set(inputPathsText.split(/\r?\n/).map((path) => path.trim()).filter(Boolean))]; void workflow.importPaths(paths, workflow.selectedRole); }}><label htmlFor="input-paths">{t("inputPathsLabel")}</label><textarea id="input-paths" rows={4} value={inputPathsText} disabled={workflow.inputBusy} spellCheck={false} aria-describedby="input-paths-hint" onChange={(event) => setInputPathsText(event.target.value)} /><p id="input-paths-hint">{t("inputPathsHint")}</p><button type="submit" className="secondary-button" disabled={workflow.inputBusy || !inputPathsText.trim()}>{t("importEnteredPaths")}</button></form></details>}
        <div className="import-workbench"><div><FrameInventory workflow={workflow} t={t} /><CalibrationGroups workflow={workflow} t={t} /></div><InputChecks workflow={workflow} t={t} /></div>
        {metadataConfirmations}
        {launchPanel("import")}
      </section>}

      {workflow.step === "inspect" && <section aria-labelledby="inspect-title" className="page"><PageHeading id="inspect-title" eyebrow={workflow.demoMode ? t("demo") : t("reviewEyebrow")} title={t("reviewTitle")} description={workflow.demoMode ? t("demoReviewDescription") : t("reviewDescription")} />
        <div className="gate-layout"><div className="gate-score-panel"><div className="gate-total"><small>{t("lightInventory")}</small><strong>{workflow.gate.pass + workflow.gate.review + workflow.gate.hardFail}</strong><span>{t("frames")}</span></div><div className="gate-bars"><GateBar disposition="PASS" value={workflow.gate.pass} total={workflow.gate.pass + workflow.gate.review + workflow.gate.hardFail} label={t("enterPipeline")} /><GateBar disposition="REVIEW" value={workflow.gate.review} total={workflow.gate.pass + workflow.gate.review + workflow.gate.hardFail} label={t("excludedDefault")} /><GateBar disposition="HARD_FAIL" value={workflow.gate.hardFail} total={workflow.gate.pass + workflow.gate.review + workflow.gate.hardFail} label={t("alwaysBlocked")} /></div></div><details className="evidence-panel"><summary><span>{t("decisionRules")}</span><small>{t("failClosed")}</small></summary><dl className="evidence-list"><div><dt>{t("cloudWall")}</dt><dd>{t("spatialStars")}</dd></div><div><dt>{t("focusTrail")}</dt><dd>{t("morphology")}</dd></div><div><dt>{t("brightness")}</dt><dd>{t("notAlone")}</dd></div><div><dt>{t("reviewRule")}</dt><dd>{t("unattendedExcluded")}</dd></div></dl></details></div>
        <InputChecks workflow={workflow} t={t} /><CalibrationGroups workflow={workflow} t={t} />
        <section className="matrix-section" aria-labelledby="matrix-title"><div className="panel-heading"><span id="matrix-title">{t("panelMatrix")}</span><small>{t("matrixCounts", { targets: targets.length, filters: filters.length, panels: workflow.matrix.length })}</small></div>{workflow.matrix.length ? <div className="matrix-scroll"><table><thead><tr><th scope="col">{t("targetLabel")}</th>{filters.map((filter) => <th scope="col" key={filter}>{filter}</th>)}</tr></thead><tbody>{targets.map((target) => <tr key={target}><th scope="row">{target}</th>{filters.map((filter) => { const cell = workflow.matrix.find((item) => item.target === target && item.filter === filter); return <td key={filter} className={cell ? "matrix-present" : "matrix-empty"}>{cell ? workflow.qualityReady ? t("panelAdmittedCounts", { admitted: cell.admittedCount, total: cell.lightCount, required: workflow.minimumAdmittedLights }) : `${cell.lightCount} ${t("frames")}` : "—"}</td>; })}</tr>)}</tbody></table></div> : <p className="empty-state">{t("noGroups")}</p>}</section>
        {!workflow.demoMode && workflow.qualityInspection && <details className="quality-frame-section" open={workflow.gate.review + workflow.gate.hardFail > 0}><summary><span>{t("frameEvidence")}</span><small>{t("qualityIssueCount", { count: issueQualityFrames.length, pass: passingQualityFrames.length })} · POLICY {workflow.qualityInspection.gatePolicyDigest.slice(7, 19)}</small></summary><div className="details-content">{workflow.gate.review > 0 && workflow.matrix.length !== 1 && <Alert title={t("multiReviewTitle")}>{t("multiReviewBody")}</Alert>}<div className="quality-frame-list">{displayedQualityFrames.map((frame) => { const approved = Boolean(frame.sourceSha256 && workflow.approvedReviewDigests.includes(frame.sourceSha256)); const canApprove = workflow.canApproveReview(frame); const unavailable = workflow.matrix.length !== 1 ? t("multiCannotApprove") : t("previewUnavailable"); return <article key={frame.path} className={`quality-frame quality-${frame.disposition.toLowerCase().replace("_", "-")}`}>{frame.previewDataUrl && <img className="quality-preview" src={frame.previewDataUrl} alt={t("previewAlt", { name: basename(frame.path) })} />}<div><span>{frame.disposition}</span><strong title={frame.path}>{basename(frame.path)}</strong><small>{frame.starCount} {t("starsLabel")} · {frame.confidence}</small></div><p>{frame.evidence.length ? frame.evidence.map((item) => item.message).slice(0, 2).join("; ") : t("noReviewEvidence")}</p>{frame.disposition === "REVIEW" && <button type="button" className="secondary-button" disabled={!canApprove} aria-pressed={approved} onClick={() => workflow.toggleReviewApproval(frame)}>{approved ? t("approvedReview") : canApprove ? t("approveReview") : unavailable}</button>}{frame.disposition === "HARD_FAIL" && <em>{t("cannotPromote")}</em>}</article>; })}</div>{passingQualityFrames.length > visiblePassFrames && <div className="pass-pagination"><span>{t("passBatchStatus", { shown: Math.min(visiblePassFrames, passingQualityFrames.length), total: passingQualityFrames.length })}</span><button type="button" className="secondary-button" onClick={() => setVisiblePassFrames((current) => current + PASS_FRAME_BATCH)}>{t("showMorePass", { count: Math.min(PASS_FRAME_BATCH, passingQualityFrames.length - visiblePassFrames) })}</button></div>}</div></details>}
        {metadataConfirmations}
        {workflow.demoMode && <Alert title={t("demoWarningTitle")}>{t("demoWarningBody")}</Alert>}
        {launchPanel("inspect")}
      </section>}

      {workflow.step === "run" && <section aria-labelledby="run-title" className="page run-page"><PageHeading id="run-title" eyebrow={t("pipeline")} title={workflow.runStatus === "CANCELLED" ? t("cancelledTitle") : workflow.runStatus === "FAILED" ? t("failedTitle") : t("runningTitle")} description={t("runDescription")} /><RunElapsed seconds={workflow.runElapsedSeconds} label={t(workflow.runStatus === "RUNNING" || workflow.runStatus === "CANCELLING" ? "runElapsed" : "runTotalTime")} /><p className="run-progress-context" role="status">{workflow.runProgress?.scope === "panel" ? t("currentPanelProgress", { index: workflow.runProgress.panelIndex ?? 0, count: workflow.runProgress.panelCount ?? 0, target: workflow.runProgress.panelTarget ?? "", filter: workflow.runProgress.panelFilter ?? "" }) : workflow.runProgress?.scope === "project" ? t("projectFinalStages") : t("overallProjectProgress")}{workflow.runProgress?.message && <small> · {workflow.runProgress.message}</small>}</p><div className="run-layout"><div className="progress-orbit" aria-label={`${workflow.overallProgress}%`}><svg viewBox="0 0 140 140" aria-hidden="true"><circle className="orbit-track" cx="70" cy="70" r="58" /><circle className="orbit-value" cx="70" cy="70" r="58" pathLength="100" strokeDasharray={`${workflow.overallProgress} 100`} /></svg><div><strong>{workflow.overallProgress}%</strong><span>{workflow.runStatus === "CANCELLED" ? "CANCELLED" : workflow.executionMode === "demo" ? t("demo") : t("overallProjectProgress")}</span></div></div><ol className="stage-list">{workflow.stages.filter((stage) => (workflow.drizzleEnabled || stage.stageId !== "drizzle") && (workflow.localNormalizationEnabled || stage.stageId !== "local-normalization")).map((stage, index) => <li key={stage.stageId} className={stage.status.toLowerCase()}><span className="stage-index">{stage.status === "DONE" ? <CheckIcon /> : String(index + 1).padStart(2, "0")}</span><div><strong>{stageLabel(stage.stageId, t)}</strong><div className="mini-track"><span style={{ width: `${stage.percent}%` }} /></div></div><em>{Math.round(stage.percent)}%</em></li>)}</ol></div>{workflow.executionMode === "demo" && <p className="mock-notice"><SparkIcon />{t("demoWarningBody")}</p>}{workflow.errorMessage && <p className="error-text" role="alert">{workflow.errorMessage}</p>}<div className="page-actions centered-actions">{workflow.runStatus === "RUNNING" && <button type="button" className="cancel-button" disabled={workflow.runLaunchBusy} onClick={() => void workflow.cancelRun()}>{t("cancel")}</button>}{["CANCELLED", "FAILED"].includes(workflow.runStatus) && <button type="button" className="secondary-button" onClick={() => workflow.setStep("import")}>{t("returnConfig")}</button>}</div></section>}

      {workflow.step === "result" && <section aria-labelledby="result-title" className="page result-page"><div className="solved-hero"><div className="solved-visual"><div className="star-field" /><span className="reticle reticle-one" /><span className="reticle reticle-two" /><TelescopeIcon /></div><div><span className="solved-pill"><CheckIcon />{workflow.executionMode === "demo" ? t("resultDemo") : t("resultSolved")}</span><h1 id="result-title">{workflow.executionMode === "demo" ? t("resultDemoTitle") : t("resultTitle")}</h1><p>{workflow.executionMode === "demo" ? t("resultDemoBody") : t("resultBody")}</p><RunElapsed seconds={workflow.runElapsedSeconds} label={t("runTotalTime")} />{workflow.firstSolved ? <dl className="wcs-grid"><div><dt>{t("center")}</dt><dd>{workflow.firstSolved.centerRaDegrees.toFixed(6)}°<br />{workflow.firstSolved.centerDecDegrees.toFixed(6)}°</dd></div><div><dt>{t("pixelScale")}</dt><dd>{workflow.firstSolved.pixelScaleArcsec.toFixed(3)}″ / px</dd></div><div><dt>{t("solveQuality")}</dt><dd>{workflow.firstSolved.rmsArcsec.toFixed(3)}″ RMS<br />{workflow.firstSolved.matchedStars} {t("starsLabel")}</dd></div></dl> : <p>{t("demoNoWcs")}</p>}</div></div>{workflow.screening && <ScreeningSection screening={workflow.screening} t={t} />}<ArtifactGrid title={t("products")} artifacts={workflow.artifacts.filter((artifact) => !["RECEIPT", "REPORT"].includes(artifact.kind))} workflow={workflow} language={language} t={t} />{workflow.artifacts.some((artifact) => ["RECEIPT", "REPORT"].includes(artifact.kind)) && <details className="progressive-panel result-details"><summary><span>{t("technicalDetails")}</span><small>SHA-256 · JSON</small></summary><div className="details-content"><ArtifactGrid artifacts={workflow.artifacts.filter((artifact) => ["RECEIPT", "REPORT"].includes(artifact.kind))} workflow={workflow} language={language} t={t} /></div></details>}{workflow.executionMode === "demo" && <p className="mock-notice"><SparkIcon />{t("demoWarningBody")}</p>}<div className="page-actions split-actions"><button type="button" className="secondary-button" onClick={workflow.clearSources}>{t("startNew")}</button><button type="button" className="primary-button" disabled={!workflow.nativeRuntime || !workflow.outputDirectory} title={workflow.outputDirectory} onClick={() => workflow.outputDirectory && void workflow.revealOutput(workflow.outputDirectory)}>{t("revealOutput", { name: workflow.outputDirectory ? basename(workflow.outputDirectory) : "—" })} <FolderIcon /></button></div></section>}
    </main><footer className="app-footer"><span>Ultra-Fast WBPP 0.1 · QC4-20260908</span><span>{t("sourcesReadonly")}</span><details className="legal-disclosure"><summary>{t("legal")}</summary><p>{t("legalBody")}</p></details></footer>
  </div>;
}

type Workflow = ReturnType<typeof useWorkflow>;

/**
 * Output location, the optional pre-run screening and the start button.  It
 * sits on the import page and again under the screening review, so a user
 * who never opens the review still has everything needed to start.
 */
function LaunchPanel({ mode, workflow, outputPathText, setOutputPathText, lightCount, t }: { mode: "import" | "inspect"; workflow: Workflow; outputPathText: string; setOutputPathText: (value: string) => void; lightCount: number; t: Translator }) {
  const catalogFraction = workflow.catalogProgress?.sizeBytes ? Math.min(1, workflow.catalogProgress.downloadedBytes / workflow.catalogProgress.sizeBytes) : 0;
  return <section className="launch-panel" aria-labelledby={`launch-title-${mode}`}>
    <div className="panel-heading"><span id={`launch-title-${mode}`}>{t("launchTitle")}</span><small>{t("launchHint")}</small></div>
    <section className="compute-panel" aria-label={t("outputLocation")}><FolderIcon /><div><small>CREATE-ONLY</small><strong>{workflow.outputParent ?? (workflow.demoMode ? t("browserNoFiles") : t("outputNotSelected"))}</strong></div><button type="button" className="secondary-button" disabled={!workflow.nativeRuntime} onClick={() => void workflow.chooseOutputParent()}>{t("chooseOutput")}</button></section>
    {workflow.nativeRuntime && <details className="progressive-panel path-entry-panel"><summary><span>{t("enterOutputPath")}</span></summary><form className="details-content path-entry-form" onSubmit={(event) => { event.preventDefault(); workflow.useOutputParentPath(outputPathText); }}><label htmlFor="output-parent-path">{t("outputPathLabel")}</label><input id="output-parent-path" value={outputPathText} disabled={workflow.runNavigationLocked} spellCheck={false} aria-describedby="output-path-hint" onChange={(event) => setOutputPathText(event.target.value)} /><p id="output-path-hint">{t("outputPathHint")}</p><button type="submit" className="secondary-button" disabled={workflow.runNavigationLocked || !outputPathText.trim()}>{t("useOutputPath")}</button></form></details>}
    <details className="progressive-panel advanced-panel" open={!workflow.solverSetupReady && workflow.nativeRuntime}><summary><span>{t("advanced")}</span><small>Drizzle · LN · WCS</small></summary><div className="details-content"><div className="toggle-stack"><label className={`feature-toggle ${workflow.drizzleEnabled ? "enabled" : ""}`}><input type="checkbox" checked={workflow.drizzleEnabled} disabled={!workflow.capabilities?.drizzleAvailable} onChange={(event) => workflow.setDrizzleEnabled(event.target.checked)} /><span><strong>{t("drizzle")}</strong><small>{t("drizzleHint")}</small></span></label><label className={`feature-toggle ${workflow.localNormalizationEnabled ? "enabled" : ""}`}><input type="checkbox" checked={workflow.localNormalizationEnabled} onChange={(event) => workflow.setLocalNormalizationEnabled(event.target.checked)} /><span><strong>{t("localNormalization")}</strong><small>{t("localNormalizationHint")}</small></span></label></div><section className="solver-setup" aria-labelledby="solver-title"><div className="panel-heading"><span id="solver-title">{t("solverSetup")}</span><div className="setup-actions"><small>{workflow.solverSetupReady ? t("ready") : t("actionRequired")}</small>{workflow.nativeRuntime && <button type="button" className="secondary-button" disabled={workflow.solverSetupBusy || workflow.catalogStatus === "DOWNLOADING" || workflow.catalogStatus === "VERIFYING"} onClick={() => void workflow.recheckSolverSetup()}>{workflow.solverSetupBusy ? t("checkingSetup") : t("recheckSetup")}</button>}</div></div><div className="solver-binaries"><SolverRow name="solve-field" ready={Boolean(workflow.solveField?.executionReady)} version={workflow.solveField?.version} path={workflow.solveField?.metadata?.probe?.path} instruction={t("solveFieldInstall")} t={t} /><SolverRow name="ASTAP" ready={Boolean(workflow.astap?.executionReady)} version={workflow.astap?.version} path={workflow.astap?.metadata?.probe?.path} instruction={t("astapDiagnostic")} t={t} /></div>
          {!workflow.nativeRuntime ? <p className="mock-notice">{t("browserNoSolver")}</p> : workflow.catalogDoctor?.ok ? <div className="catalog-ready"><CheckIcon /><div><strong>{t("catalogReady")}</strong><p>{workflow.catalogDoctor.catalogRoot}</p></div></div> : workflow.recommendedCatalog ? <div className="catalog-install"><div><strong>{t("catalogInstallTitle")}</strong><p>{t("catalogInstallBody")}</p></div><div className="terms-box"><p>{workflow.recommendedCatalog.providerTerms.summary}</p><a href={workflow.recommendedCatalog.providerTerms.url} onClick={(event) => { event.preventDefault(); void workflow.openCatalogTerms(workflow.recommendedCatalog!.providerTerms.url); }}>{t("viewTerms")}</a><label><input type="checkbox" checked={workflow.catalogTermsAccepted} disabled={workflow.catalogStatus === "DOWNLOADING" || workflow.catalogStatus === "VERIFYING"} onChange={(event) => workflow.setCatalogTermsAccepted(event.target.checked)} />{t("acceptTerms", { id: workflow.recommendedCatalog.providerTerms.acceptanceId })}</label></div>{workflow.catalogStatus === "DOWNLOADING" && <div className="catalog-progress" role="status"><progress max={1} value={catalogFraction} /><span>{workflow.catalogProgress ? `${workflow.catalogProgress.artifactId} · ${(catalogFraction * 100).toFixed(1)}%` : t("waitProgress")}</span><button type="button" className="cancel-button" onClick={() => void workflow.cancelCatalogInstall()}>{t("cancelDownload")}</button></div>}{workflow.catalogStatus === "VERIFYING" && <p role="status">{t("verifyingCatalog")}</p>}{workflow.catalogStatus !== "DOWNLOADING" && workflow.catalogStatus !== "VERIFYING" && <button type="button" className="primary-button" disabled={!workflow.catalogTermsAccepted} onClick={() => void workflow.startCatalogInstall()}>{t("downloadCatalog", { size: formatBytes(workflow.recommendedCatalog.totalSizeBytes, t) })}</button>}</div> : <p className="error-text" role="alert">{t("noCatalogManifest")}</p>}{workflow.catalogError && <p className="error-text" role="alert">{workflow.catalogError}</p>}
        </section><section className="compute-panel" aria-label={t("computeBackend")}><CpuIcon /><div><small>{t("computeBackend").toUpperCase()}</small><strong>{workflow.capabilities?.chip ?? t("detectingHardware")}</strong></div><span>{workflow.capabilities?.cpuBackend ?? "Portable CPU"}</span><span>{workflow.capabilities?.gpuBackend ?? "GPU probe"}</span><em>{workflow.capabilities?.platform === "browser" ? t("demoNoCompute") : workflow.capabilities?.platform === "windows" ? t("windowsBoundary") : workflow.capabilities?.optimizationTier === "M3_PRO_TUNED" ? t("m3Optimized") : t("appleGeneric")}</em></section></div></details>
    {!workflow.canStart && !workflow.demoMode && <div className="blockers" role="status"><strong>{t("blockers")}</strong><ul>{!workflow.capabilities?.available && <li>{workflow.capabilities?.unavailableReason ?? t("blockerEngine")}</li>}{!workflow.calibrationReady && <li>{t("blockerCalibration")}</li>}{!workflow.allRequiredConfirmed && <li>{t("blockerTypes")}</li>}{workflow.matrix.length === 0 && <li>{t("blockerLights")}</li>}{workflow.insufficientPanels.map((cell) => <li key={cell.panelId}>{t("insufficientPanelLights", { target: cell.target, filter: cell.filter, count: workflow.qualityReady ? cell.admittedCount : cell.lightCount, required: workflow.minimumAdmittedLights })}</li>)}{!workflow.solverSetupReady && <li>{t("blockerSolver")}</li>}{!workflow.outputParent && <li>{t("blockerOutput")}</li>}{!workflow.masterOverridesReady && <li>{t("blockerMaster")}</li>}{workflow.cfaBlockedAssets.length > 0 && <li>{t("blockerOsc")}</li>}</ul>{workflow.qualityReady && workflow.insufficientPanels.length > 0 && mode !== "inspect" && <button type="button" className="secondary-button" onClick={() => workflow.setStep("inspect")}>{t("reviewLightAdmission")}</button>}</div>}
    <div className="page-actions split-actions"><div className="demo-control">{mode === "inspect" ? <button type="button" className="text-button" onClick={() => workflow.setStep("import")}>{t("back")}</button> : <>{workflow.browserDemoAvailable && <button type="button" className="text-button" onClick={workflow.loadDemo}>{t("loadDemo")}</button>}{workflow.importedTotal > 0 && <button type="button" className="text-button danger-text" disabled={workflow.inputBusy} onClick={workflow.clearSources}>{t("clear")}</button>}</>}<span>{workflow.nativeRuntime ? t("readonlyOutput") : t("browserNoFiles")}</span></div><div className="launch-actions">{mode === "import" && <button type="button" className="secondary-button" disabled={!workflow.canInspect || !workflow.allRequiredConfirmed || workflow.qualityBusy} onClick={() => void workflow.runInspection()}>{workflow.qualityBusy ? t("inspecting") : workflow.qualityReady ? t("viewQualityResults") : t("inspect", { count: lightCount || "" })}</button>}<button type="button" className="primary-button" disabled={!workflow.canStart} onClick={() => void workflow.startRun()}><PlayIcon />{t("start")}<ChevronIcon /></button></div></div>
  </section>;
}

/** The run's own screening: how many Lights went in and why the others did not. */
function ScreeningSection({ screening, t }: { screening: ScreeningSummary; t: Translator }) {
  const decided = screening.frames;
  return <section className="screening-section" aria-labelledby="screening-title">
    <div className="panel-heading"><span id="screening-title">{t("screeningTitle")}</span><small>{t("screeningSummary", { admitted: screening.admitted, excluded: screening.excluded })}</small></div>
    {decided.length === 0 ? <p className="screening-clean">{t("screeningAllPassed")}</p> : <div className="quality-frame-list">{decided.map((frame) => <article key={`${frame.target ?? ""}/${frame.name}`} className={`quality-frame quality-${frame.disposition.toLowerCase().replace("_", "-")}`}>{frame.previewDataUrl && <img className="quality-preview" src={frame.previewDataUrl} alt={t("previewAlt", { name: frame.name })} />}<div><span>{frame.admitted ? t("screeningAdmittedReview") : frame.disposition}</span><strong title={frame.name}>{frame.name}</strong><small>{frame.target ? `${frame.target} · ` : ""}{frame.starCount ?? "—"} {t("starsLabel")}</small></div><p>{frame.evidence.length ? frame.evidence.slice(0, 2).join("; ") : frame.summary || t("noReviewEvidence")}</p></article>)}</div>}
    {decided.some((frame) => frame.disposition === "REVIEW" && !frame.admitted) && <p className="screening-hint">{t("screeningReviewHint")}</p>}
  </section>;
}
function ArtifactGrid({ title, artifacts, workflow, t }: { title?: string; artifacts: Workflow["artifacts"]; workflow: Workflow; language: UiLanguage; t: Translator }) { return <div className="artifact-section"><div className="panel-heading"><span>{title}</span><small>{t("verifiedFiles", { count: artifacts.length })}</small></div><div className="artifact-grid">{artifacts.map((artifact) => <article key={artifact.path}><span className={`artifact-kind kind-${artifact.kind.toLowerCase()}`}><FileIcon /></span><div><small>{artifactLabel(artifact.kind, t)}</small><strong>{artifact.name}</strong><p>{artifact.filter ? `${artifact.target ?? ""} · ${artifact.filter} · ` : ""}{artifact.detail}</p></div><button type="button" disabled={!workflow.nativeRuntime} title={artifact.path} aria-label={t("showInFinder", { name: artifact.name })} onClick={() => void workflow.revealOutput(artifact.path)}><ChevronIcon /></button></article>)}</div></div>; }
function MasterForm({ item, update, confirm, reset, t }: { item: MasterMetadataOverride; update: (patch: Partial<MasterMetadataOverride>) => void; confirm: () => void; reset: () => void; t: Translator }) {
  const numeric = (field: "gain" | "offset" | "temperatureCelsius" | "exposureSeconds", label: string) => <label><span>{label}</span><input type="number" step="any" inputMode="decimal" placeholder={t("notRecorded")} value={item[field] ?? ""} onChange={(event) => update({ [field]: optionalNumber(event.target.value) })} /></label>;
  const additiveMaster = item.role === "MASTER_BIAS" || item.role === "MASTER_DARK";
  const chooseNumericDomain = (value: string) => {
    if (value === "NORMALIZED_UNIT") update({ numericDomain: value, normalizedUnitScale: 1 });
    else if (value === "SENSOR_CODE") update({ numericDomain: value, normalizedUnitScale: 65535 });
    else update({ numericDomain: null, normalizedUnitScale: null });
  };
  return <article className={`master-form ${item.confirmed ? "confirmed" : ""}`}>
    <header><div><small>{item.role}</small><strong title={item.sourcePath}>{basename(item.sourcePath)}</strong></div><span>{item.confirmed ? item.needsMetadataOverride ? t("shaBound") : t("useFileMetadata") : t("needsConfirmation")}</span></header>
    {!item.confirmed && <p className="suggestion-note" role="status">{t("suggestion")}</p>}
    <div className="metadata-fields"><label><span>{t("cameraLabel")}</span><input value={item.camera} onChange={(event) => update({ camera: event.target.value })} /></label>{numeric("gain", t("gainLabel"))}{numeric("offset", t("offsetLabel"))}<label><span>{t("binningLabel")}</span><span className="inline-inputs"><input type="number" min="1" inputMode="numeric" placeholder={t("notRecorded")} value={item.binning[0] ?? ""} onChange={(event) => update({ binning: [optionalNumber(event.target.value), item.binning[1]] })} /><input type="number" min="1" inputMode="numeric" placeholder={t("notRecorded")} value={item.binning[1] ?? ""} onChange={(event) => update({ binning: [item.binning[0], optionalNumber(event.target.value)] })} /></span></label><label><span>{t("filterLabel")}</span><input value={item.filter} onChange={(event) => update({ filter: event.target.value })} /></label><label><span>{t("cfaLabel")}</span><input value={item.cfaPattern} onChange={(event) => update({ cfaPattern: event.target.value })} /></label><label><span>{t("readoutLabel")}</span><input value={item.readoutMode} onChange={(event) => update({ readoutMode: event.target.value })} /></label>{numeric("temperatureCelsius", t("temperatureLabel"))}{numeric("exposureSeconds", t("exposureLabel"))}</div>
    {item.role === "MASTER_DARK" && <fieldset className="bias-choice"><legend>{t("darkBiasQuestion")}</legend><label><input type="radio" name={`bias-${item.sourceSha256}`} checked={item.biasIncluded === true} onChange={() => update({ biasIncluded: true })} />{t("yesBias")}</label><label><input type="radio" name={`bias-${item.sourceSha256}`} checked={item.biasIncluded === false} onChange={() => update({ biasIncluded: false })} />{t("noBias")}</label><label><input type="radio" name={`bias-${item.sourceSha256}`} checked={item.biasIncluded === null} onChange={() => update({ biasIncluded: null })} />{t("unknownBlocked")}</label><p>{t("darkBiasHelp")}</p></fieldset>}
    {additiveMaster && <fieldset className="bias-choice unit-choice"><legend>{t("pixelUnits")}</legend><label><select aria-label={t("pixelUnits")} value={item.numericDomain ?? "AUTO"} onChange={(event) => chooseNumericDomain(event.target.value)}><option value="AUTO">{t("pixelUnitsAuto")}</option><option value="NORMALIZED_UNIT">{t("pixelUnitsNormalized")}</option><option value="SENSOR_CODE">{t("pixelUnitsSensor")}</option></select></label>{item.numericDomain === "SENSOR_CODE" && <label><span>{t("pixelUnitsScale")}</span><input type="number" step="any" className="unit-scale-input" inputMode="decimal" value={item.normalizedUnitScale ?? ""} onChange={(event) => update({ normalizedUnitScale: optionalNumber(event.target.value) })} /></label>}<p>{t("pixelUnitsHelp")}</p></fieldset>}
    <div className="dialog-actions"><button type="button" className="secondary-button" disabled={item.confirmed} onClick={confirm}>{t("confirmAndBind")}</button>{item.needsMetadataOverride && <button type="button" className="text-button" onClick={reset}>{t("restoreFileMetadata")}</button>}</div>
  </article>;
}
function SolverRow({ name, ready, version, path, instruction, t }: { name: string; ready: boolean; version?: string; path?: string | null; instruction: string; t: Translator }) { return <article className="solver-row"><span className={`runtime-dot ${ready ? "online" : ""}`} /><div><strong>{name} {ready ? t("executable") : t("notReady")}</strong><p>{ready ? `${version ?? "?"} · ${path ?? t("ready")}` : instruction}</p></div></article>; }
function Alert({ title, children }: { title: string; children: React.ReactNode }) { return <aside className="review-callout" role="alert"><span className="review-symbol">!</span><div><strong>{title}</strong><p>{children}</p></div></aside>; }
function PageHeading({ id, eyebrow, title, description }: { id: string; eyebrow: string; title: string; description: string }) { return <header className="page-heading"><small>{eyebrow}</small><h1 id={id}>{title}</h1><p>{description}</p></header>; }
function GateBar({ disposition, value, total, label }: { disposition: GateDisposition; value: number; total: number; label: string }) { const percent = total ? (value / total) * 100 : 0; return <div className={`gate-bar gate-${disposition.toLowerCase().replace("_", "-")}`}><div><span>{disposition}</span><em>{label}</em><strong>{value}</strong></div><div className="bar-track"><span style={{ width: `${percent}%` }} /></div><small>{percent.toFixed(1)}%</small></div>; }

export default App;
